# Generated by Django 3.1.7 on 2021-03-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasePortuguese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_portuguese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordPortuguese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_portuguese', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordKokama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_kokama', models.CharField(max_length=50)),
                ('pronunciation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.pronunciationtype')),
                ('translations', models.ManyToManyField(through='dictionary.Translate', to='dictionary.WordPortuguese')),
            ],
        ),
        migrations.AddField(
            model_name='translate',
            name='word_kokama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.wordkokama'),
        ),
        migrations.AddField(
            model_name='translate',
            name='word_portuguese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.wordportuguese'),
        ),
        migrations.CreateModel(
            name='PhraseKokama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_kokama', models.TextField()),
                ('phrase_portuguese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.phraseportuguese')),
                ('word_kokama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to='dictionary.wordkokama')),
            ],
        ),
    ]
