# Generated by Django 3.1.7 on 2021-03-27 20:06

from django.db import migrations
from django.core.management import call_command

fixtures = [
    'pronunciation_type',
]

def load_fixtures(apps, schema_editor):
    for fixture in fixtures:
        call_command('loaddata', fixture, app_label='dictionary') 

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]