# Generated by Django 3.1.7 on 2021-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordPortuguese',
            new_name='Palavra_Portugues',
        ),
    ]
