# Generated by Django 3.1.7 on 2021-03-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210313_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase_Portuguese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasePortuguese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Palavra_Kokama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordKokama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pronuncia_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciationType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='traduz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kokama', models.ManyToManyField(to='dictionary.Palavra_Kokama')),
                ('portuguese', models.ManyToManyField(to='dictionary.Palavra_Portugues')),
            ],
        ),
        migrations.AddField(
            model_name='palavra_kokama',
            name='pronunciationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.pronuncia_tipo'),
        ),
        migrations.CreateModel(
            name='Frase_Kokama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phraseKokama', models.TextField()),
                ('phrasePortuguese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.frase_portuguese')),
                ('wordKokama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.palavra_kokama')),
            ],
        ),
    ]
