# Generated by Django 3.1.7 on 2021-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20210313_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduz',
            name='kokama',
            field=models.ManyToManyField(to='dictionary.PALAVRA_KOKAMA'),
        ),
        migrations.AlterField(
            model_name='traduz',
            name='portuguese',
            field=models.ManyToManyField(to='dictionary.PALAVRA_PORTUGUES'),
        ),
    ]
