# Generated by Django 3.1.7 on 2021-03-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210313_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frase_Kokama',
            new_name='PhraseKokama',
        ),
        migrations.RenameModel(
            old_name='FRASE_PORTUGUES',
            new_name='PhrasePortuguese',
        ),
        migrations.RenameModel(
            old_name='Palavra_Portugues',
            new_name='PronunciationType',
        ),
        migrations.RenameModel(
            old_name='Palavra_Kokama',
            new_name='WordKokama',
        ),
        migrations.RenameModel(
            old_name='Pronuncia_Tipo',
            new_name='WordPortuguese',
        ),
        migrations.RenameField(
            model_name='pronunciationtype',
            old_name='wordPortuguese',
            new_name='pronunciationType',
        ),
        migrations.RenameField(
            model_name='wordportuguese',
            old_name='pronunciationType',
            new_name='wordPortuguese',
        ),
    ]
