# Generated by Django 3.1.7 on 2021-03-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20210313_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduz',
            name='portuguese',
            field=models.ManyToManyField(to='dictionary.WordPortuguese'),
        ),
        migrations.AlterField(
            model_name='wordkokama',
            name='pronunciationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.pronunciationtype'),
        ),
    ]
