# This is a basic workflow to help you get started with Actions

name: "pre-release"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get SonarCloud Metrics
        run: wget https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2020.2-Projeto-Kokama-Traducao&metricKeys=files,functions,complexity,coverage,ncloc,comment_lines_density,duplicated_lines_density,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500 -O fga-eps-mds-2020_2-Projeto-Kokama-Traducao-"${{date("d-m-Y")}}".json
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "pre-release"
          files: |
            fga-eps-mds-2020_2-Projeto-Kokama-Traducao-"${{date("d-m-Y")}}".json
